name: Deploy to Github Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: actions/setup-node@v4
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: oven-sh/setup-bun@v2
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: bun install
        run: bun install
      - name: npx quartz build
        run: npx quartz build
      - name: actions/upload-pages-artifact@v3
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deployment
        id: deployment
        uses: actions/deploy-pages@v4
